name: release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: pack
        env:
          RELEASE_NOTES: ${{ github.event.release.body }}
        run: dotnet pack FryProxy/FryProxy.fsproj --nologo -o packages

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          path: out/*
          retention-days: 7
      
      - name: push
        run: 
          dotnet nuget push packages/*
          -k ${{ secrets.NUGET_API_KEY }}
          -s https://api.nuget.org/v3/index.json
          --skip-duplicate 